#!/usr/bin/env python3
"""Export the mod's database rows, on top of the stub base database (tests/stub.py), to tests/gameinfo_data.lua
for the offline Lua harness."""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
MOD = HERE.parent
sys.path.insert(0, str(HERE))
from stub import build_stub  # noqa: E402

SQL = ["SQL/FN_Settings.sql", "SQL/FN_Schema.sql", "SQL/FN_Data.sql", "SQL/FN_Nations.sql", "SQL/FN_Organisations.sql",
       "SQL/FN_Independence.sql", "SQL/FN_Perks.sql"]

# Table -> columns to export (None = all). The DLL-shaped tables are wide, so only what the Lua reads is kept.
EXPORT = {
    "Eras": None, "Civilizations": None, "MinorCivilizations": None, "Resources": None, "GameSpeeds": None,
    "MajorBlocksMinor": None, "UnitClasses": None, "Policy_UnitClassReplacements": None,
    "Policies": ["ID", "Type", "Description", "Help"],
    "Units": ["ID", "Type", "Class", "Description", "Help", "Combat", "Domain", "PolicyType"],
    "FormableNation_Settings": None, "FormableNation_EraSettings": None, "FormableNation_ColonialStates": None,
    "FormableNations": None, "FormableNation_ClaimGroups": None, "FormableNation_Claims": None,
    "FormableNation_Organisations": None, "FormableNation_OrganisationMembers": None,
}


def main():
    db = build_stub()
    for f in SQL:
        db.executescript((MOD / f).read_text(encoding="utf-8"))
    out = ["-- Generated by make_gameinfo.py; do not edit.", "GI_DATA = {"]
    for table, cols in EXPORT.items():
        cur = db.execute(f"SELECT {', '.join(cols) if cols else '*'} FROM {table}")
        names = [c[0] for c in cur.description]
        out.append(f"  {table} = {{")
        for row in cur.fetchall():
            fields = []
            for c, v in zip(names, row):
                if v is None:
                    continue
                fields.append(f"{c} = {v!r}" if isinstance(v, (int, float)) else f'{c} = "{v}"')
            out.append("    { " + ", ".join(fields) + " },")
        out.append("  },")
    out.append("}")
    (HERE / "gameinfo_data.lua").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {HERE / 'gameinfo_data.lua'}")


if __name__ == "__main__":
    main()
