-- Formable Nations v0.5: alliances, organisations of Depth ALLIANCE with charter terms (columns in FN_Organisations.sql).
-- Logic: UI/FN_Alliances.lua. Every alliance keeps member cohesion (credibility) and forbids war between members.

INSERT INTO FormableNation_Organisations
	(Type, Depth, Title, Help, Quote, MinEra, MaxEra, MinMembers, OpenBorders, MemberCohesion, NoWarBetweenMembers,
	 Obligation, Scope, NoSeparatePeace, Burden, Hegemonic, Custom)
VALUES
	('ORG_DELIAN_LEAGUE', 'ALLIANCE', 'TXT_KEY_FN_ORG_DELIAN_TITLE', NULL, 'TXT_KEY_FN_ORG_DELIAN_QUOTE',
		'ERA_CLASSICAL', 'ERA_CLASSICAL', 2, 0, 1, 1, 'DEFENCE', 'REGIONAL', 0, 'TRIBUTE', 1, 0),
	('ORG_LOMBARD_LEAGUE', 'ALLIANCE', 'TXT_KEY_FN_ORG_LOMBARD_TITLE', NULL, 'TXT_KEY_FN_ORG_LOMBARD_QUOTE',
		'ERA_MEDIEVAL', 'ERA_MEDIEVAL', 2, 1, 1, 1, 'DEFENCE', 'REGIONAL', 1, 'NONE', 0, 0),
	('ORG_HOLY_LEAGUE', 'ALLIANCE', 'TXT_KEY_FN_ORG_HOLY_LEAGUE_TITLE', NULL, 'TXT_KEY_FN_ORG_HOLY_LEAGUE_QUOTE',
		'ERA_RENAISSANCE', 'ERA_RENAISSANCE', 2, 0, 1, 1, 'FULL', 'GLOBAL', 0, 'NONE', 0, 0),
	('ORG_TRIPLE_ALLIANCE', 'ALLIANCE', 'TXT_KEY_FN_ORG_TRIPLE_ALLIANCE_TITLE', NULL, 'TXT_KEY_FN_ORG_TRIPLE_ALLIANCE_QUOTE',
		'ERA_INDUSTRIAL', 'ERA_MODERN', 2, 0, 1, 1, 'DEFENCE', 'GLOBAL', 0, 'NONE', 0, 0),
	('ORG_TRIPLE_ENTENTE', 'ALLIANCE', 'TXT_KEY_FN_ORG_TRIPLE_ENTENTE_TITLE', NULL, 'TXT_KEY_FN_ORG_TRIPLE_ENTENTE_QUOTE',
		'ERA_INDUSTRIAL', 'ERA_MODERN', 2, 0, 1, 1, 'CONSULT', 'GLOBAL', 0, 'NONE', 0, 0),
	('ORG_NATO', 'ALLIANCE', 'TXT_KEY_FN_ORG_NATO_TITLE', NULL, 'TXT_KEY_FN_ORG_NATO_QUOTE',
		'ERA_POSTMODERN', NULL, 3, 1, 1, 1, 'DEFENCE', 'REGIONAL', 0, 'TARGET', 0, 0),
	('ORG_WARSAW_PACT', 'ALLIANCE', 'TXT_KEY_FN_ORG_WARSAW_PACT_TITLE', NULL, 'TXT_KEY_FN_ORG_WARSAW_PACT_QUOTE',
		'ERA_POSTMODERN', NULL, 3, 1, 1, 1, 'DEFENCE', 'REGIONAL', 1, 'NONE', 1, 0),
	-- Player-drafted pacts: any civilization or City-State may join; name and terms are set at founding.
	('ORG_PACT_1', 'ALLIANCE', 'TXT_KEY_FN_ORG_PACT_TITLE', NULL, NULL, 'ERA_MEDIEVAL', NULL, 2, 1, 1, 1, 'DEFENCE', 'GLOBAL', 0, 'NONE', 0, 1),
	('ORG_PACT_2', 'ALLIANCE', 'TXT_KEY_FN_ORG_PACT_TITLE', NULL, NULL, 'ERA_MEDIEVAL', NULL, 2, 1, 1, 1, 'DEFENCE', 'GLOBAL', 0, 'NONE', 0, 1),
	('ORG_PACT_3', 'ALLIANCE', 'TXT_KEY_FN_ORG_PACT_TITLE', NULL, NULL, 'ERA_MEDIEVAL', NULL, 2, 1, 1, 1, 'DEFENCE', 'GLOBAL', 0, 'NONE', 0, 1);

CREATE TEMP TABLE FN_PactMembers (OrganisationType text, CivilizationType text, MinorCivType text);
INSERT INTO FN_PactMembers VALUES
	-- Delian League (478 BC): Athens and the Aegean
	('ORG_DELIAN_LEAGUE', 'CIVILIZATION_GREECE', NULL), ('ORG_DELIAN_LEAGUE', 'CIVILIZATION_BYZANTIUM', NULL),
	('ORG_DELIAN_LEAGUE', NULL, 'MINOR_CIV_ARGOS'), ('ORG_DELIAN_LEAGUE', NULL, 'MINOR_CIV_PERGE'),
	('ORG_DELIAN_LEAGUE', NULL, 'MINOR_CIV_RAGUSA'), ('ORG_DELIAN_LEAGUE', NULL, 'MINOR_CIV_VALLETTA'),
	-- Lombard League (1167): the communes of northern Italy
	('ORG_LOMBARD_LEAGUE', 'CIVILIZATION_VENICE', NULL), ('ORG_LOMBARD_LEAGUE', 'CIVILIZATION_ROME', NULL),
	('ORG_LOMBARD_LEAGUE', NULL, 'MINOR_CIV_MILAN'), ('ORG_LOMBARD_LEAGUE', NULL, 'MINOR_CIV_GENOA'),
	('ORG_LOMBARD_LEAGUE', NULL, 'MINOR_CIV_FLORENCE'), ('ORG_LOMBARD_LEAGUE', NULL, 'MINOR_CIV_VENICE'),
	('ORG_LOMBARD_LEAGUE', NULL, 'MINOR_CIV_VATICAN_CITY'),
	-- Holy League (1571 and 1684)
	('ORG_HOLY_LEAGUE', 'CIVILIZATION_SPAIN', NULL), ('ORG_HOLY_LEAGUE', 'CIVILIZATION_VENICE', NULL),
	('ORG_HOLY_LEAGUE', 'CIVILIZATION_AUSTRIA', NULL), ('ORG_HOLY_LEAGUE', 'CIVILIZATION_POLAND', NULL),
	('ORG_HOLY_LEAGUE', 'CIVILIZATION_RUSSIA', NULL),
	('ORG_HOLY_LEAGUE', NULL, 'MINOR_CIV_VATICAN_CITY'), ('ORG_HOLY_LEAGUE', NULL, 'MINOR_CIV_GENOA'),
	('ORG_HOLY_LEAGUE', NULL, 'MINOR_CIV_VALLETTA'), ('ORG_HOLY_LEAGUE', NULL, 'MINOR_CIV_VENICE'),
	-- Triple Alliance (1882)
	('ORG_TRIPLE_ALLIANCE', 'CIVILIZATION_GERMANY', NULL), ('ORG_TRIPLE_ALLIANCE', 'CIVILIZATION_AUSTRIA', NULL),
	('ORG_TRIPLE_ALLIANCE', 'CIVILIZATION_ROME', NULL), ('ORG_TRIPLE_ALLIANCE', 'CIVILIZATION_OTTOMAN', NULL),
	('ORG_TRIPLE_ALLIANCE', NULL, 'MINOR_CIV_SOFIA'), ('ORG_TRIPLE_ALLIANCE', NULL, 'MINOR_CIV_BUCHAREST'),
	-- Triple Entente (1907)
	('ORG_TRIPLE_ENTENTE', 'CIVILIZATION_FRANCE', NULL), ('ORG_TRIPLE_ENTENTE', 'CIVILIZATION_ENGLAND', NULL),
	('ORG_TRIPLE_ENTENTE', 'CIVILIZATION_RUSSIA', NULL), ('ORG_TRIPLE_ENTENTE', 'CIVILIZATION_JAPAN', NULL),
	('ORG_TRIPLE_ENTENTE', NULL, 'MINOR_CIV_BELGRADE'), ('ORG_TRIPLE_ENTENTE', NULL, 'MINOR_CIV_BRUSSELS'),
	-- NATO (1949) and later members
	('ORG_NATO', 'CIVILIZATION_AMERICA', NULL), ('ORG_NATO', 'CIVILIZATION_ENGLAND', NULL), ('ORG_NATO', 'CIVILIZATION_FRANCE', NULL),
	('ORG_NATO', 'CIVILIZATION_NETHERLANDS', NULL), ('ORG_NATO', 'CIVILIZATION_DENMARK', NULL), ('ORG_NATO', 'CIVILIZATION_PORTUGAL', NULL),
	('ORG_NATO', 'CIVILIZATION_ROME', NULL), ('ORG_NATO', 'CIVILIZATION_GREECE', NULL), ('ORG_NATO', 'CIVILIZATION_OTTOMAN', NULL),
	('ORG_NATO', 'CIVILIZATION_GERMANY', NULL), ('ORG_NATO', 'CIVILIZATION_SPAIN', NULL), ('ORG_NATO', 'CIVILIZATION_POLAND', NULL),
	('ORG_NATO', 'CIVILIZATION_SWEDEN', NULL),
	('ORG_NATO', NULL, 'MINOR_CIV_BRUSSELS'), ('ORG_NATO', NULL, 'MINOR_CIV_ANTWERP'), ('ORG_NATO', NULL, 'MINOR_CIV_LISBON'),
	('ORG_NATO', NULL, 'MINOR_CIV_OSLO'), ('ORG_NATO', NULL, 'MINOR_CIV_COPENHAGEN'), ('ORG_NATO', NULL, 'MINOR_CIV_QUEBEC_CITY'),
	('ORG_NATO', NULL, 'MINOR_CIV_VANCOUVER'), ('ORG_NATO', NULL, 'MINOR_CIV_HELSINKI'), ('ORG_NATO', NULL, 'MINOR_CIV_STOCKHOLM'),
	('ORG_NATO', NULL, 'MINOR_CIV_PRAGUE'), ('ORG_NATO', NULL, 'MINOR_CIV_BUDAPEST'), ('ORG_NATO', NULL, 'MINOR_CIV_BRATISLAVA'),
	('ORG_NATO', NULL, 'MINOR_CIV_WARSAW'), ('ORG_NATO', NULL, 'MINOR_CIV_VILNIUS'), ('ORG_NATO', NULL, 'MINOR_CIV_RIGA'),
	('ORG_NATO', NULL, 'MINOR_CIV_SOFIA'), ('ORG_NATO', NULL, 'MINOR_CIV_BUCHAREST'), ('ORG_NATO', NULL, 'MINOR_CIV_RAGUSA'),
	-- Warsaw Pact (1955)
	('ORG_WARSAW_PACT', 'CIVILIZATION_RUSSIA', NULL), ('ORG_WARSAW_PACT', 'CIVILIZATION_POLAND', NULL),
	('ORG_WARSAW_PACT', NULL, 'MINOR_CIV_WARSAW'), ('ORG_WARSAW_PACT', NULL, 'MINOR_CIV_PRAGUE'),
	('ORG_WARSAW_PACT', NULL, 'MINOR_CIV_BUDAPEST'), ('ORG_WARSAW_PACT', NULL, 'MINOR_CIV_BRATISLAVA'),
	('ORG_WARSAW_PACT', NULL, 'MINOR_CIV_SOFIA'), ('ORG_WARSAW_PACT', NULL, 'MINOR_CIV_BUCHAREST');
INSERT INTO FormableNation_OrganisationMembers (OrganisationType, CivilizationType, MinorCivType)
	SELECT OrganisationType, CivilizationType, MinorCivType FROM FN_PactMembers
	WHERE CivilizationType IN (SELECT Type FROM Civilizations) OR MinorCivType IN (SELECT Type FROM MinorCivilizations);
DROP TABLE FN_PactMembers;
