-- Formable Nations v0.1 content. Bonuses target half to one social policy; see the design doc's balance notes.

-- Hidden bonus carriers. PolicyBranchType stays NULL, so VP treats them as dummies (no cost increase, not in the tree).
INSERT INTO Policies (Type, Description, Help, IsDummy) VALUES
	('POLICY_FN_KREWO',           'TXT_KEY_FN_KREWO_TITLE',           'TXT_KEY_FN_KREWO_HELP',           1),
	('POLICY_FN_COMMONWEALTH',    'TXT_KEY_FN_COMMONWEALTH_TITLE',    'TXT_KEY_FN_COMMONWEALTH_HELP',    1),
	('POLICY_FN_HABSBURG',        'TXT_KEY_FN_HABSBURG_TITLE',        'TXT_KEY_FN_HABSBURG_HELP',        1),
	('POLICY_FN_AUSTRIA_HUNGARY', 'TXT_KEY_FN_AUSTRIA_HUNGARY_TITLE', 'TXT_KEY_FN_AUSTRIA_HUNGARY_HELP', 1),
	('POLICY_FN_HRE',             'TXT_KEY_FN_HRE_TITLE',             'TXT_KEY_FN_HRE_HELP',             1),
	('POLICY_FN_GERMAN_EMPIRE',   'TXT_KEY_FN_GERMAN_EMPIRE_TITLE',   'TXT_KEY_FN_GERMAN_EMPIRE_HELP',   1),
	('POLICY_FN_GREAT_BRITAIN',   'TXT_KEY_FN_GREAT_BRITAIN_TITLE',   'TXT_KEY_FN_GREAT_BRITAIN_HELP',   1),
	('POLICY_FN_UNION_OF_CROWNS', 'TXT_KEY_FN_UNION_OF_CROWNS_TITLE', 'TXT_KEY_FN_UNION_OF_CROWNS_HELP', 1);

UPDATE Policies SET FreeWCVotes = 1 WHERE Type = 'POLICY_FN_COMMONWEALTH';
UPDATE Policies SET MilitaryProductionModifier = 10 WHERE Type = 'POLICY_FN_GERMAN_EMPIRE';
UPDATE Policies SET EmbarkedExtraMoves = 1 WHERE Type = 'POLICY_FN_GREAT_BRITAIN';

INSERT INTO Policy_CapitalYieldChanges (PolicyType, YieldType, Yield) VALUES
	('POLICY_FN_KREWO', 'YIELD_CULTURE', 2),
	('POLICY_FN_KREWO', 'YIELD_FAITH', 2),
	('POLICY_FN_HRE', 'YIELD_CULTURE', 2),
	('POLICY_FN_UNION_OF_CROWNS', 'YIELD_CULTURE', 2),
	('POLICY_FN_UNION_OF_CROWNS', 'YIELD_GOLD', 2);

INSERT INTO Policy_YieldModifiers (PolicyType, YieldType, Yield) VALUES
	('POLICY_FN_COMMONWEALTH', 'YIELD_CULTURE', 5),
	('POLICY_FN_HABSBURG', 'YIELD_GOLD', 5),
	('POLICY_FN_AUSTRIA_HUNGARY', 'YIELD_PRODUCTION', 5),
	('POLICY_FN_AUSTRIA_HUNGARY', 'YIELD_SCIENCE', 5),
	('POLICY_FN_HRE', 'YIELD_FAITH', 10),
	('POLICY_FN_GERMAN_EMPIRE', 'YIELD_PRODUCTION', 5),
	('POLICY_FN_GREAT_BRITAIN', 'YIELD_GOLD', 5);

INSERT INTO FormableNations
	(Type, Chain, Stage, Tier, IsUnion, CivilizationType, Title, Description, ShortDescription, Adjective, Help, Quote, MinEra, MaxEra, PrereqStage, PrereqTurns, PolicyType)
VALUES
	('FN_KREWO', 'POLAND', 1, 1, 1, 'CIVILIZATION_POLAND', 'TXT_KEY_FN_KREWO_TITLE',
		NULL, NULL, NULL,
		'TXT_KEY_FN_KREWO_HELP', 'TXT_KEY_FN_KREWO_QUOTE', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', NULL, 0, 'POLICY_FN_KREWO'),
	('FN_COMMONWEALTH', 'POLAND', 2, 2, 0, 'CIVILIZATION_POLAND', 'TXT_KEY_FN_COMMONWEALTH_TITLE',
		'TXT_KEY_FN_COMMONWEALTH_DESC', 'TXT_KEY_FN_COMMONWEALTH_SHORT', 'TXT_KEY_FN_COMMONWEALTH_ADJ',
		'TXT_KEY_FN_COMMONWEALTH_HELP', 'TXT_KEY_FN_COMMONWEALTH_QUOTE', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL', 'FN_KREWO', 10, 'POLICY_FN_COMMONWEALTH'),
	('FN_HABSBURG', 'AUSTRIA', 1, 1, 1, 'CIVILIZATION_AUSTRIA', 'TXT_KEY_FN_HABSBURG_TITLE',
		'TXT_KEY_FN_HABSBURG_DESC', 'TXT_KEY_FN_HABSBURG_SHORT', 'TXT_KEY_FN_HABSBURG_ADJ',
		'TXT_KEY_FN_HABSBURG_HELP', 'TXT_KEY_FN_HABSBURG_QUOTE', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL', NULL, 0, 'POLICY_FN_HABSBURG'),
	('FN_AUSTRIA_HUNGARY', 'AUSTRIA', 2, 2, 0, 'CIVILIZATION_AUSTRIA', 'TXT_KEY_FN_AUSTRIA_HUNGARY_TITLE',
		'TXT_KEY_FN_AUSTRIA_HUNGARY_DESC', 'TXT_KEY_FN_AUSTRIA_HUNGARY_SHORT', 'TXT_KEY_FN_AUSTRIA_HUNGARY_ADJ',
		'TXT_KEY_FN_AUSTRIA_HUNGARY_HELP', 'TXT_KEY_FN_AUSTRIA_HUNGARY_QUOTE', 'ERA_INDUSTRIAL', 'ERA_MODERN', 'FN_HABSBURG', 10, 'POLICY_FN_AUSTRIA_HUNGARY'),
	('FN_HRE', 'GERMANY', 1, 1, 1, 'CIVILIZATION_GERMANY', 'TXT_KEY_FN_HRE_TITLE',
		'TXT_KEY_FN_HRE_DESC', 'TXT_KEY_FN_HRE_SHORT', 'TXT_KEY_FN_HRE_ADJ',
		'TXT_KEY_FN_HRE_HELP', 'TXT_KEY_FN_HRE_QUOTE', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', NULL, 0, 'POLICY_FN_HRE'),
	('FN_GERMAN_EMPIRE', 'GERMANY', 2, 2, 0, 'CIVILIZATION_GERMANY', 'TXT_KEY_FN_GERMAN_EMPIRE_TITLE',
		'TXT_KEY_FN_GERMAN_EMPIRE_DESC', 'TXT_KEY_FN_GERMAN_EMPIRE_SHORT', 'TXT_KEY_FN_GERMAN_EMPIRE_ADJ',
		'TXT_KEY_FN_GERMAN_EMPIRE_HELP', 'TXT_KEY_FN_GERMAN_EMPIRE_QUOTE', 'ERA_INDUSTRIAL', 'ERA_MODERN', NULL, 0, 'POLICY_FN_GERMAN_EMPIRE'),
	('FN_UNION_OF_CROWNS', 'ENGLAND', 1, 1, 1, 'CIVILIZATION_ENGLAND', 'TXT_KEY_FN_UNION_OF_CROWNS_TITLE',
		NULL, NULL, NULL,
		'TXT_KEY_FN_UNION_OF_CROWNS_HELP', 'TXT_KEY_FN_UNION_OF_CROWNS_QUOTE', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL', NULL, 0, 'POLICY_FN_UNION_OF_CROWNS'),
	('FN_GREAT_BRITAIN', 'ENGLAND', 2, 2, 0, 'CIVILIZATION_ENGLAND', 'TXT_KEY_FN_GREAT_BRITAIN_TITLE',
		'TXT_KEY_FN_GREAT_BRITAIN_DESC', 'TXT_KEY_FN_GREAT_BRITAIN_SHORT', 'TXT_KEY_FN_GREAT_BRITAIN_ADJ',
		'TXT_KEY_FN_GREAT_BRITAIN_HELP', 'TXT_KEY_FN_GREAT_BRITAIN_QUOTE', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL', 'FN_UNION_OF_CROWNS', 10, 'POLICY_FN_GREAT_BRITAIN');

INSERT INTO FormableNation_ClaimGroups (FormableType, GroupID, NumRequired, Description) VALUES
	('FN_KREWO', 1, 1, 'TXT_KEY_FN_GROUP_LITHUANIA'),
	('FN_COMMONWEALTH', 1, 1, 'TXT_KEY_FN_GROUP_LITHUANIA'),
	('FN_HABSBURG', 1, 1, 'TXT_KEY_FN_GROUP_HUNGARY'),
	('FN_AUSTRIA_HUNGARY', 1, 1, 'TXT_KEY_FN_GROUP_HUNGARY'),
	('FN_HRE', 1, 1, 'TXT_KEY_FN_GROUP_CORONATION'),
	('FN_HRE', 2, 2, 'TXT_KEY_FN_GROUP_IMPERIAL_ESTATES'),
	('FN_GERMAN_EMPIRE', 1, 1, 'TXT_KEY_FN_GROUP_SAXONY'),
	('FN_UNION_OF_CROWNS', 1, 1, 'TXT_KEY_FN_GROUP_SCOTLAND'),
	('FN_GREAT_BRITAIN', 1, 1, 'TXT_KEY_FN_GROUP_SCOTLAND');

INSERT INTO FormableNation_Claims (FormableType, GroupID, MinorCivType, CivilizationType, Mode) VALUES
	('FN_KREWO', 1, 'MINOR_CIV_VILNIUS', NULL, 'UNION'),
	('FN_COMMONWEALTH', 1, 'MINOR_CIV_VILNIUS', NULL, 'ABSORB'),
	('FN_HABSBURG', 1, 'MINOR_CIV_BUDAPEST', NULL, 'UNION'),
	('FN_HABSBURG', 1, 'MINOR_CIV_BRATISLAVA', NULL, 'UNION'),
	('FN_AUSTRIA_HUNGARY', 1, 'MINOR_CIV_BUDAPEST', NULL, 'ABSORB'),
	('FN_AUSTRIA_HUNGARY', 1, 'MINOR_CIV_BRATISLAVA', NULL, 'ABSORB'),
	('FN_HRE', 1, 'MINOR_CIV_VATICAN_CITY', NULL, 'ALLY'),
	('FN_HRE', 1, NULL, 'CIVILIZATION_ROME', 'OWN'),
	('FN_HRE', 2, 'MINOR_CIV_WITTENBERG', NULL, 'UNION'),
	('FN_HRE', 2, 'MINOR_CIV_PRAGUE', NULL, 'UNION'),
	('FN_HRE', 2, 'MINOR_CIV_ZURICH', NULL, 'UNION'),
	('FN_HRE', 2, 'MINOR_CIV_GENEVA', NULL, 'UNION'),
	('FN_HRE', 2, 'MINOR_CIV_MILAN', NULL, 'UNION'),
	('FN_HRE', 2, 'MINOR_CIV_GENOA', NULL, 'UNION'),
	('FN_HRE', 2, 'MINOR_CIV_FLORENCE', NULL, 'UNION'),
	('FN_HRE', 2, 'MINOR_CIV_ANTWERP', NULL, 'UNION'),
	('FN_HRE', 2, 'MINOR_CIV_BRUSSELS', NULL, 'UNION'),
	('FN_GERMAN_EMPIRE', 1, 'MINOR_CIV_WITTENBERG', NULL, 'ABSORB'),
	-- Scotland is Edinburgh the City-State when the Celts are absent (VP blocks it while they play), else the Celtic capital.
	('FN_UNION_OF_CROWNS', 1, 'MINOR_CIV_EDINBURGH', NULL, 'UNION'),
	('FN_UNION_OF_CROWNS', 1, NULL, 'CIVILIZATION_CELTS', 'UNION'),
	('FN_GREAT_BRITAIN', 1, 'MINOR_CIV_EDINBURGH', NULL, 'ABSORB'),
	('FN_GREAT_BRITAIN', 1, NULL, 'CIVILIZATION_CELTS', 'UNION');
