-- Formable Nations v0.4: more nations, one or two stages each, across all eras. Bonuses follow FN_Data.sql's scale
-- (half to one social policy); Tier II stages also get the proclamation golden age (FN_Perks.sql).

INSERT INTO Policies (Type, Description, Help, IsDummy) VALUES
	('POLICY_FN_SUMER_AKKAD',      'TXT_KEY_FN_SUMER_AKKAD_TITLE',      'TXT_KEY_FN_SUMER_AKKAD_HELP',      1),
	('POLICY_FN_KALMAR',           'TXT_KEY_FN_KALMAR_TITLE',           'TXT_KEY_FN_KALMAR_HELP',           1),
	('POLICY_FN_SWEDISH_EMPIRE',   'TXT_KEY_FN_SWEDISH_EMPIRE_TITLE',   'TXT_KEY_FN_SWEDISH_EMPIRE_HELP',   1),
	('POLICY_FN_RUSSIAN_EMPIRE',   'TXT_KEY_FN_RUSSIAN_EMPIRE_TITLE',   'TXT_KEY_FN_RUSSIAN_EMPIRE_HELP',   1),
	('POLICY_FN_IBERIAN_UNION',    'TXT_KEY_FN_IBERIAN_UNION_TITLE',    'TXT_KEY_FN_IBERIAN_UNION_HELP',    1),
	('POLICY_FN_UNITED_NETHERLANDS','TXT_KEY_FN_UNITED_NETHERLANDS_TITLE','TXT_KEY_FN_UNITED_NETHERLANDS_HELP',1),
	('POLICY_FN_ITALY',            'TXT_KEY_FN_ITALY_TITLE',            'TXT_KEY_FN_ITALY_HELP',            1),
	('POLICY_FN_YUAN',             'TXT_KEY_FN_YUAN_TITLE',             'TXT_KEY_FN_YUAN_HELP',             1);

UPDATE Policies SET MilitaryProductionModifier = 10 WHERE Type = 'POLICY_FN_SWEDISH_EMPIRE';

INSERT INTO Policy_CapitalYieldChanges (PolicyType, YieldType, Yield) VALUES
	('POLICY_FN_SUMER_AKKAD', 'YIELD_SCIENCE', 2),
	('POLICY_FN_SUMER_AKKAD', 'YIELD_FOOD', 2),
	('POLICY_FN_KALMAR', 'YIELD_PRODUCTION', 2),
	('POLICY_FN_KALMAR', 'YIELD_GOLD', 2),
	('POLICY_FN_SWEDISH_EMPIRE', 'YIELD_CULTURE', 2),
	('POLICY_FN_RUSSIAN_EMPIRE', 'YIELD_CULTURE', 2),
	('POLICY_FN_UNITED_NETHERLANDS', 'YIELD_GOLD', 3),
	('POLICY_FN_ITALY', 'YIELD_CULTURE', 3);

INSERT INTO Policy_YieldModifiers (PolicyType, YieldType, Yield) VALUES
	('POLICY_FN_RUSSIAN_EMPIRE', 'YIELD_SCIENCE', 5),
	('POLICY_FN_IBERIAN_UNION', 'YIELD_GOLD', 5),
	('POLICY_FN_UNITED_NETHERLANDS', 'YIELD_PRODUCTION', 5),
	('POLICY_FN_ITALY', 'YIELD_CULTURE', 5),
	('POLICY_FN_YUAN', 'YIELD_GOLD', 5),
	('POLICY_FN_YUAN', 'YIELD_SCIENCE', 5);

INSERT INTO FormableNations
	(Type, Chain, Stage, Tier, IsUnion, CivilizationType, Title, Description, ShortDescription, Adjective, Help, Quote, MinEra, MaxEra, PrereqStage, PrereqTurns, PolicyType)
VALUES
	('FN_SUMER_AKKAD', 'BABYLON', 1, 2, 0, 'CIVILIZATION_BABYLON', 'TXT_KEY_FN_SUMER_AKKAD_TITLE',
		'TXT_KEY_FN_SUMER_AKKAD_DESC', 'TXT_KEY_FN_SUMER_AKKAD_SHORT', 'TXT_KEY_FN_SUMER_AKKAD_ADJ',
		'TXT_KEY_FN_SUMER_AKKAD_HELP', 'TXT_KEY_FN_SUMER_AKKAD_QUOTE', 'ERA_ANCIENT', 'ERA_CLASSICAL', NULL, 0, 'POLICY_FN_SUMER_AKKAD'),
	('FN_KALMAR', 'DENMARK', 1, 1, 1, 'CIVILIZATION_DENMARK', 'TXT_KEY_FN_KALMAR_TITLE',
		NULL, NULL, NULL,
		'TXT_KEY_FN_KALMAR_HELP', 'TXT_KEY_FN_KALMAR_QUOTE', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', NULL, 0, 'POLICY_FN_KALMAR'),
	('FN_SWEDISH_EMPIRE', 'SWEDEN', 1, 2, 0, 'CIVILIZATION_SWEDEN', 'TXT_KEY_FN_SWEDISH_EMPIRE_TITLE',
		'TXT_KEY_FN_SWEDISH_EMPIRE_DESC', 'TXT_KEY_FN_SWEDISH_EMPIRE_SHORT', 'TXT_KEY_FN_SWEDISH_EMPIRE_ADJ',
		'TXT_KEY_FN_SWEDISH_EMPIRE_HELP', 'TXT_KEY_FN_SWEDISH_EMPIRE_QUOTE', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL', NULL, 0, 'POLICY_FN_SWEDISH_EMPIRE'),
	('FN_RUSSIAN_EMPIRE', 'RUSSIA', 1, 2, 0, 'CIVILIZATION_RUSSIA', 'TXT_KEY_FN_RUSSIAN_EMPIRE_TITLE',
		'TXT_KEY_FN_RUSSIAN_EMPIRE_DESC', 'TXT_KEY_FN_RUSSIAN_EMPIRE_SHORT', 'TXT_KEY_FN_RUSSIAN_EMPIRE_ADJ',
		'TXT_KEY_FN_RUSSIAN_EMPIRE_HELP', 'TXT_KEY_FN_RUSSIAN_EMPIRE_QUOTE', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL', NULL, 0, 'POLICY_FN_RUSSIAN_EMPIRE'),
	('FN_IBERIAN_UNION', 'SPAIN', 1, 1, 1, 'CIVILIZATION_SPAIN', 'TXT_KEY_FN_IBERIAN_UNION_TITLE',
		NULL, NULL, NULL,
		'TXT_KEY_FN_IBERIAN_UNION_HELP', 'TXT_KEY_FN_IBERIAN_UNION_QUOTE', 'ERA_RENAISSANCE', 'ERA_RENAISSANCE', NULL, 0, 'POLICY_FN_IBERIAN_UNION'),
	('FN_UNITED_NETHERLANDS', 'NETHERLANDS', 1, 2, 0, 'CIVILIZATION_NETHERLANDS', 'TXT_KEY_FN_UNITED_NETHERLANDS_TITLE',
		'TXT_KEY_FN_UNITED_NETHERLANDS_DESC', 'TXT_KEY_FN_UNITED_NETHERLANDS_SHORT', 'TXT_KEY_FN_UNITED_NETHERLANDS_ADJ',
		'TXT_KEY_FN_UNITED_NETHERLANDS_HELP', 'TXT_KEY_FN_UNITED_NETHERLANDS_QUOTE', 'ERA_INDUSTRIAL', 'ERA_INDUSTRIAL', NULL, 0, 'POLICY_FN_UNITED_NETHERLANDS'),
	('FN_ITALY', 'ROME', 1, 2, 0, 'CIVILIZATION_ROME', 'TXT_KEY_FN_ITALY_TITLE',
		'TXT_KEY_FN_ITALY_DESC', 'TXT_KEY_FN_ITALY_SHORT', 'TXT_KEY_FN_ITALY_ADJ',
		'TXT_KEY_FN_ITALY_HELP', 'TXT_KEY_FN_ITALY_QUOTE', 'ERA_INDUSTRIAL', 'ERA_MODERN', NULL, 0, 'POLICY_FN_ITALY'),
	('FN_YUAN', 'MONGOL', 1, 2, 0, 'CIVILIZATION_MONGOL', 'TXT_KEY_FN_YUAN_TITLE',
		'TXT_KEY_FN_YUAN_DESC', 'TXT_KEY_FN_YUAN_SHORT', 'TXT_KEY_FN_YUAN_ADJ',
		'TXT_KEY_FN_YUAN_HELP', 'TXT_KEY_FN_YUAN_QUOTE', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', NULL, 0, 'POLICY_FN_YUAN');

INSERT INTO FormableNation_ClaimGroups (FormableType, GroupID, NumRequired, Description) VALUES
	('FN_SUMER_AKKAD', 1, 1, 'TXT_KEY_FN_GROUP_SUMER'),
	('FN_KALMAR', 1, 1, 'TXT_KEY_FN_GROUP_SWEDEN'),
	('FN_SWEDISH_EMPIRE', 1, 1, 'TXT_KEY_FN_GROUP_LIVONIA'),
	('FN_RUSSIAN_EMPIRE', 1, 1, 'TXT_KEY_FN_GROUP_LIVONIA'),
	('FN_IBERIAN_UNION', 1, 1, 'TXT_KEY_FN_GROUP_PORTUGAL'),
	('FN_UNITED_NETHERLANDS', 1, 1, 'TXT_KEY_FN_GROUP_SOUTHERN_NETHERLANDS'),
	('FN_ITALY', 1, 2, 'TXT_KEY_FN_GROUP_ITALIAN_STATES'),
	('FN_YUAN', 1, 1, 'TXT_KEY_FN_GROUP_CHINA');

INSERT INTO FormableNation_Claims (FormableType, GroupID, MinorCivType, CivilizationType, Mode) VALUES
	('FN_SUMER_AKKAD', 1, 'MINOR_CIV_UR', NULL, 'ABSORB'),
	-- Sweden is Stockholm the City-State when the Swedes are absent (VP blocks it while they play), else their capital.
	('FN_KALMAR', 1, 'MINOR_CIV_STOCKHOLM', NULL, 'UNION'),
	('FN_KALMAR', 1, NULL, 'CIVILIZATION_SWEDEN', 'UNION'),
	-- Riga: the prize of the Great Northern War. Sweden and Russia compete for it.
	('FN_SWEDISH_EMPIRE', 1, 'MINOR_CIV_RIGA', NULL, 'ABSORB'),
	('FN_RUSSIAN_EMPIRE', 1, 'MINOR_CIV_RIGA', NULL, 'ABSORB'),
	('FN_IBERIAN_UNION', 1, 'MINOR_CIV_LISBON', NULL, 'UNION'),
	('FN_IBERIAN_UNION', 1, NULL, 'CIVILIZATION_PORTUGAL', 'UNION'),
	('FN_UNITED_NETHERLANDS', 1, 'MINOR_CIV_BRUSSELS', NULL, 'ABSORB'),
	('FN_UNITED_NETHERLANDS', 1, 'MINOR_CIV_ANTWERP', NULL, 'ABSORB'),
	('FN_ITALY', 1, 'MINOR_CIV_FLORENCE', NULL, 'ABSORB'),
	('FN_ITALY', 1, 'MINOR_CIV_MILAN', NULL, 'ABSORB'),
	('FN_ITALY', 1, 'MINOR_CIV_GENOA', NULL, 'ABSORB'),
	('FN_ITALY', 1, 'MINOR_CIV_VENICE', NULL, 'ABSORB'),
	('FN_YUAN', 1, NULL, 'CIVILIZATION_CHINA', 'OWN');

-- v0.5: formations for more civilizations. Where a civ's homeland City-State is blocked while that civ plays, the
-- claim pairs the City-State with the civ's capital (e.g. Palatium or Rome's capital), as for Scotland.
INSERT INTO Policies (Type, Description, Help, IsDummy) VALUES
	('POLICY_FN_ABBASID',         'TXT_KEY_FN_ABBASID_TITLE',         'TXT_KEY_FN_ABBASID_HELP',         1),
	('POLICY_FN_NEO_ASSYRIA',     'TXT_KEY_FN_NEO_ASSYRIA_TITLE',     'TXT_KEY_FN_NEO_ASSYRIA_HELP',     1),
	('POLICY_FN_ACHAEMENID',      'TXT_KEY_FN_ACHAEMENID_TITLE',      'TXT_KEY_FN_ACHAEMENID_HELP',      1),
	('POLICY_FN_PHOENICIAN',      'TXT_KEY_FN_PHOENICIAN_TITLE',      'TXT_KEY_FN_PHOENICIAN_HELP',      1),
	('POLICY_FN_RENOVATIO',       'TXT_KEY_FN_RENOVATIO_TITLE',       'TXT_KEY_FN_RENOVATIO_HELP',       1),
	('POLICY_FN_GRAND_EMPIRE',    'TXT_KEY_FN_GRAND_EMPIRE_TITLE',    'TXT_KEY_FN_GRAND_EMPIRE_HELP',    1),
	('POLICY_FN_UK_PORTUGAL_BRAZIL','TXT_KEY_FN_UK_PORTUGAL_BRAZIL_TITLE','TXT_KEY_FN_UK_PORTUGAL_BRAZIL_HELP',1),
	('POLICY_FN_MAJAPAHIT',       'TXT_KEY_FN_MAJAPAHIT_TITLE',       'TXT_KEY_FN_MAJAPAHIT_HELP',       1),
	('POLICY_FN_AYUTTHAYA',       'TXT_KEY_FN_AYUTTHAYA_TITLE',       'TXT_KEY_FN_AYUTTHAYA_HELP',       1),
	('POLICY_FN_SAADI',           'TXT_KEY_FN_SAADI_TITLE',           'TXT_KEY_FN_SAADI_HELP',           1),
	('POLICY_FN_KAYSER_I_RUM',    'TXT_KEY_FN_KAYSER_I_RUM_TITLE',    'TXT_KEY_FN_KAYSER_I_RUM_HELP',    1),
	('POLICY_FN_STATO_DA_MAR',    'TXT_KEY_FN_STATO_DA_MAR_TITLE',    'TXT_KEY_FN_STATO_DA_MAR_HELP',    1);

UPDATE Policies SET MilitaryProductionModifier = 10 WHERE Type IN ('POLICY_FN_NEO_ASSYRIA', 'POLICY_FN_GRAND_EMPIRE');

INSERT INTO Policy_CapitalYieldChanges (PolicyType, YieldType, Yield) VALUES
	('POLICY_FN_ABBASID', 'YIELD_SCIENCE', 3),
	('POLICY_FN_NEO_ASSYRIA', 'YIELD_SCIENCE', 2),
	('POLICY_FN_ACHAEMENID', 'YIELD_CULTURE', 2),
	('POLICY_FN_PHOENICIAN', 'YIELD_GOLD', 3),
	('POLICY_FN_RENOVATIO', 'YIELD_CULTURE', 3),
	('POLICY_FN_RENOVATIO', 'YIELD_FAITH', 2),
	('POLICY_FN_GRAND_EMPIRE', 'YIELD_CULTURE', 2),
	('POLICY_FN_UK_PORTUGAL_BRAZIL', 'YIELD_GOLD', 3),
	('POLICY_FN_MAJAPAHIT', 'YIELD_GOLD', 2),
	('POLICY_FN_MAJAPAHIT', 'YIELD_CULTURE', 2),
	('POLICY_FN_AYUTTHAYA', 'YIELD_CULTURE', 2),
	('POLICY_FN_AYUTTHAYA', 'YIELD_FAITH', 2),
	('POLICY_FN_SAADI', 'YIELD_GOLD', 3),
	('POLICY_FN_KAYSER_I_RUM', 'YIELD_CULTURE', 3),
	('POLICY_FN_STATO_DA_MAR', 'YIELD_GOLD', 3);

INSERT INTO Policy_YieldModifiers (PolicyType, YieldType, Yield) VALUES
	('POLICY_FN_ABBASID', 'YIELD_SCIENCE', 5),
	('POLICY_FN_ACHAEMENID', 'YIELD_GOLD', 5),
	('POLICY_FN_PHOENICIAN', 'YIELD_GOLD', 5),
	('POLICY_FN_RENOVATIO', 'YIELD_FAITH', 5),
	('POLICY_FN_UK_PORTUGAL_BRAZIL', 'YIELD_GOLD', 5),
	('POLICY_FN_AYUTTHAYA', 'YIELD_CULTURE', 5),
	('POLICY_FN_SAADI', 'YIELD_GOLD', 5),
	('POLICY_FN_KAYSER_I_RUM', 'YIELD_SCIENCE', 5),
	('POLICY_FN_STATO_DA_MAR', 'YIELD_GOLD', 5);
UPDATE Policies SET InternalTradeRouteYieldModifier = 15 WHERE Type = 'POLICY_FN_ACHAEMENID'; -- the Royal Road

INSERT INTO FormableNations
	(Type, Chain, Stage, Tier, IsUnion, CivilizationType, Title, Description, ShortDescription, Adjective, Help, Quote, MinEra, MaxEra, PrereqStage, PrereqTurns, PolicyType)
VALUES
	('FN_ABBASID', 'ARABIA', 1, 2, 0, 'CIVILIZATION_ARABIA', 'TXT_KEY_FN_ABBASID_TITLE',
		'TXT_KEY_FN_ABBASID_DESC', 'TXT_KEY_FN_ABBASID_SHORT', 'TXT_KEY_FN_ABBASID_ADJ',
		'TXT_KEY_FN_ABBASID_HELP', 'TXT_KEY_FN_ABBASID_QUOTE', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', NULL, 0, 'POLICY_FN_ABBASID'),
	('FN_NEO_ASSYRIA', 'ASSYRIA', 1, 2, 0, 'CIVILIZATION_ASSYRIA', 'TXT_KEY_FN_NEO_ASSYRIA_TITLE',
		'TXT_KEY_FN_NEO_ASSYRIA_DESC', 'TXT_KEY_FN_NEO_ASSYRIA_SHORT', 'TXT_KEY_FN_NEO_ASSYRIA_ADJ',
		'TXT_KEY_FN_NEO_ASSYRIA_HELP', 'TXT_KEY_FN_NEO_ASSYRIA_QUOTE', 'ERA_ANCIENT', 'ERA_CLASSICAL', NULL, 0, 'POLICY_FN_NEO_ASSYRIA'),
	('FN_ACHAEMENID', 'PERSIA', 1, 2, 0, 'CIVILIZATION_PERSIA', 'TXT_KEY_FN_ACHAEMENID_TITLE',
		'TXT_KEY_FN_ACHAEMENID_DESC', 'TXT_KEY_FN_ACHAEMENID_SHORT', 'TXT_KEY_FN_ACHAEMENID_ADJ',
		'TXT_KEY_FN_ACHAEMENID_HELP', 'TXT_KEY_FN_ACHAEMENID_QUOTE', 'ERA_ANCIENT', 'ERA_CLASSICAL', NULL, 0, 'POLICY_FN_ACHAEMENID'),
	('FN_PHOENICIAN', 'CARTHAGE', 1, 1, 1, 'CIVILIZATION_CARTHAGE', 'TXT_KEY_FN_PHOENICIAN_TITLE',
		NULL, NULL, NULL,
		'TXT_KEY_FN_PHOENICIAN_HELP', 'TXT_KEY_FN_PHOENICIAN_QUOTE', 'ERA_ANCIENT', 'ERA_CLASSICAL', NULL, 0, 'POLICY_FN_PHOENICIAN'),
	('FN_RENOVATIO', 'BYZANTIUM', 1, 2, 0, 'CIVILIZATION_BYZANTIUM', 'TXT_KEY_FN_RENOVATIO_TITLE',
		'TXT_KEY_FN_RENOVATIO_DESC', 'TXT_KEY_FN_RENOVATIO_SHORT', 'TXT_KEY_FN_RENOVATIO_ADJ',
		'TXT_KEY_FN_RENOVATIO_HELP', 'TXT_KEY_FN_RENOVATIO_QUOTE', 'ERA_CLASSICAL', 'ERA_MEDIEVAL', NULL, 0, 'POLICY_FN_RENOVATIO'),
	('FN_GRAND_EMPIRE', 'FRANCE', 1, 1, 1, 'CIVILIZATION_FRANCE', 'TXT_KEY_FN_GRAND_EMPIRE_TITLE',
		NULL, NULL, NULL,
		'TXT_KEY_FN_GRAND_EMPIRE_HELP', 'TXT_KEY_FN_GRAND_EMPIRE_QUOTE', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL', NULL, 0, 'POLICY_FN_GRAND_EMPIRE'),
	('FN_UK_PORTUGAL_BRAZIL', 'PORTUGAL', 1, 1, 1, 'CIVILIZATION_PORTUGAL', 'TXT_KEY_FN_UK_PORTUGAL_BRAZIL_TITLE',
		'TXT_KEY_FN_UK_PORTUGAL_BRAZIL_DESC', 'TXT_KEY_FN_UK_PORTUGAL_BRAZIL_SHORT', 'TXT_KEY_FN_UK_PORTUGAL_BRAZIL_ADJ',
		'TXT_KEY_FN_UK_PORTUGAL_BRAZIL_HELP', 'TXT_KEY_FN_UK_PORTUGAL_BRAZIL_QUOTE', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL', NULL, 0, 'POLICY_FN_UK_PORTUGAL_BRAZIL'),
	('FN_UK_BRAZIL_PORTUGAL', 'BRAZIL', 1, 1, 1, 'CIVILIZATION_BRAZIL', 'TXT_KEY_FN_UK_PORTUGAL_BRAZIL_TITLE',
		'TXT_KEY_FN_UK_PORTUGAL_BRAZIL_DESC', 'TXT_KEY_FN_UK_PORTUGAL_BRAZIL_SHORT', 'TXT_KEY_FN_UK_PORTUGAL_BRAZIL_ADJ',
		'TXT_KEY_FN_UK_PORTUGAL_BRAZIL_HELP', 'TXT_KEY_FN_UK_PORTUGAL_BRAZIL_QUOTE', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL', NULL, 0, 'POLICY_FN_UK_PORTUGAL_BRAZIL'),
	('FN_MAJAPAHIT', 'INDONESIA', 1, 1, 1, 'CIVILIZATION_INDONESIA', 'TXT_KEY_FN_MAJAPAHIT_TITLE',
		NULL, NULL, NULL,
		'TXT_KEY_FN_MAJAPAHIT_HELP', 'TXT_KEY_FN_MAJAPAHIT_QUOTE', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', NULL, 0, 'POLICY_FN_MAJAPAHIT'),
	('FN_AYUTTHAYA', 'SIAM', 1, 1, 1, 'CIVILIZATION_SIAM', 'TXT_KEY_FN_AYUTTHAYA_TITLE',
		NULL, NULL, NULL,
		'TXT_KEY_FN_AYUTTHAYA_HELP', 'TXT_KEY_FN_AYUTTHAYA_QUOTE', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', NULL, 0, 'POLICY_FN_AYUTTHAYA'),
	('FN_SAADI', 'MOROCCO', 1, 2, 0, 'CIVILIZATION_MOROCCO', 'TXT_KEY_FN_SAADI_TITLE',
		'TXT_KEY_FN_SAADI_DESC', 'TXT_KEY_FN_SAADI_SHORT', 'TXT_KEY_FN_SAADI_ADJ',
		'TXT_KEY_FN_SAADI_HELP', 'TXT_KEY_FN_SAADI_QUOTE', 'ERA_RENAISSANCE', 'ERA_RENAISSANCE', NULL, 0, 'POLICY_FN_SAADI'),
	('FN_KAYSER_I_RUM', 'OTTOMAN', 1, 2, 0, 'CIVILIZATION_OTTOMAN', 'TXT_KEY_FN_KAYSER_I_RUM_TITLE',
		NULL, NULL, NULL,
		'TXT_KEY_FN_KAYSER_I_RUM_HELP', 'TXT_KEY_FN_KAYSER_I_RUM_QUOTE', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', NULL, 0, 'POLICY_FN_KAYSER_I_RUM'),
	('FN_STATO_DA_MAR', 'VENICE', 1, 1, 1, 'CIVILIZATION_VENICE', 'TXT_KEY_FN_STATO_DA_MAR_TITLE',
		NULL, NULL, NULL,
		'TXT_KEY_FN_STATO_DA_MAR_HELP', 'TXT_KEY_FN_STATO_DA_MAR_QUOTE', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', NULL, 0, 'POLICY_FN_STATO_DA_MAR');

INSERT INTO FormableNation_ClaimGroups (FormableType, GroupID, NumRequired, Description) VALUES
	('FN_ABBASID', 1, 2, 'TXT_KEY_FN_GROUP_LEVANT'),
	('FN_NEO_ASSYRIA', 1, 1, 'TXT_KEY_FN_GROUP_PHOENICIA'),
	('FN_ACHAEMENID', 1, 1, 'TXT_KEY_FN_GROUP_BABYLONIA'),
	('FN_PHOENICIAN', 1, 1, 'TXT_KEY_FN_GROUP_PHOENICIA'),
	('FN_RENOVATIO', 1, 1, 'TXT_KEY_FN_GROUP_ROME'),
	('FN_RENOVATIO', 2, 1, 'TXT_KEY_FN_GROUP_AFRICA'),
	('FN_GRAND_EMPIRE', 1, 2, 'TXT_KEY_FN_GROUP_SATELLITES'),
	('FN_UK_PORTUGAL_BRAZIL', 1, 1, 'TXT_KEY_FN_GROUP_BRAZIL'),
	('FN_UK_BRAZIL_PORTUGAL', 1, 1, 'TXT_KEY_FN_GROUP_PORTUGAL'),
	('FN_MAJAPAHIT', 1, 2, 'TXT_KEY_FN_GROUP_NUSANTARA'),
	('FN_AYUTTHAYA', 1, 2, 'TXT_KEY_FN_GROUP_MALAY_STATES'),
	('FN_SAADI', 1, 1, 'TXT_KEY_FN_GROUP_SONGHAI'),
	('FN_KAYSER_I_RUM', 1, 1, 'TXT_KEY_FN_GROUP_CONSTANTINOPLE'),
	('FN_STATO_DA_MAR', 1, 2, 'TXT_KEY_FN_GROUP_STATO_DA_MAR');

INSERT INTO FormableNation_Claims (FormableType, GroupID, MinorCivType, CivilizationType, Mode) VALUES
	('FN_ABBASID', 1, 'MINOR_CIV_SIDON', NULL, 'ABSORB'),
	('FN_ABBASID', 1, 'MINOR_CIV_TYRE', NULL, 'ABSORB'),
	('FN_ABBASID', 1, 'MINOR_CIV_BYBLOS', NULL, 'ABSORB'),
	('FN_NEO_ASSYRIA', 1, 'MINOR_CIV_SIDON', NULL, 'ABSORB'),
	('FN_NEO_ASSYRIA', 1, 'MINOR_CIV_TYRE', NULL, 'ABSORB'),
	('FN_NEO_ASSYRIA', 1, 'MINOR_CIV_BYBLOS', NULL, 'ABSORB'),
	('FN_ACHAEMENID', 1, 'MINOR_CIV_UR', NULL, 'ABSORB'),
	('FN_ACHAEMENID', 1, NULL, 'CIVILIZATION_BABYLON', 'OWN'),
	('FN_PHOENICIAN', 1, 'MINOR_CIV_TYRE', NULL, 'UNION'),
	('FN_PHOENICIAN', 1, 'MINOR_CIV_SIDON', NULL, 'UNION'),
	('FN_PHOENICIAN', 1, 'MINOR_CIV_BYBLOS', NULL, 'UNION'),
	-- Rome: Palatium when the Romans are absent (VP blocks it while they play), else Rome's capital. Africa: likewise Utica or Carthage.
	('FN_RENOVATIO', 1, 'MINOR_CIV_PALATIUM', NULL, 'ABSORB'),
	('FN_RENOVATIO', 1, NULL, 'CIVILIZATION_ROME', 'OWN'),
	('FN_RENOVATIO', 2, 'MINOR_CIV_UTICA', NULL, 'ABSORB'),
	('FN_RENOVATIO', 2, NULL, 'CIVILIZATION_CARTHAGE', 'OWN'),
	('FN_GRAND_EMPIRE', 1, 'MINOR_CIV_WITTENBERG', NULL, 'UNION'),
	('FN_GRAND_EMPIRE', 1, 'MINOR_CIV_MILAN', NULL, 'UNION'),
	('FN_GRAND_EMPIRE', 1, 'MINOR_CIV_ZURICH', NULL, 'UNION'),
	('FN_GRAND_EMPIRE', 1, 'MINOR_CIV_GENEVA', NULL, 'UNION'),
	('FN_GRAND_EMPIRE', 1, 'MINOR_CIV_BRUSSELS', NULL, 'UNION'),
	('FN_GRAND_EMPIRE', 1, 'MINOR_CIV_WARSAW', NULL, 'UNION'),
	('FN_UK_PORTUGAL_BRAZIL', 1, 'MINOR_CIV_RIO_DE_JANEIRO', NULL, 'UNION'),
	('FN_UK_PORTUGAL_BRAZIL', 1, NULL, 'CIVILIZATION_BRAZIL', 'UNION'),
	('FN_UK_BRAZIL_PORTUGAL', 1, 'MINOR_CIV_LISBON', NULL, 'UNION'),
	('FN_UK_BRAZIL_PORTUGAL', 1, NULL, 'CIVILIZATION_PORTUGAL', 'UNION'),
	('FN_MAJAPAHIT', 1, 'MINOR_CIV_MALACCA', NULL, 'UNION'),
	('FN_MAJAPAHIT', 1, 'MINOR_CIV_SINGAPORE', NULL, 'UNION'),
	('FN_MAJAPAHIT', 1, 'MINOR_CIV_KUALA_LUMPUR', NULL, 'UNION'),
	('FN_MAJAPAHIT', 1, 'MINOR_CIV_MANILA', NULL, 'UNION'),
	('FN_AYUTTHAYA', 1, 'MINOR_CIV_MALACCA', NULL, 'UNION'),
	('FN_AYUTTHAYA', 1, 'MINOR_CIV_KUALA_LUMPUR', NULL, 'UNION'),
	('FN_AYUTTHAYA', 1, 'MINOR_CIV_SINGAPORE', NULL, 'UNION'),
	('FN_SAADI', 1, 'MINOR_CIV_DJENNE', NULL, 'ABSORB'),
	('FN_SAADI', 1, NULL, 'CIVILIZATION_SONGHAI', 'OWN'),
	('FN_KAYSER_I_RUM', 1, NULL, 'CIVILIZATION_BYZANTIUM', 'OWN'),
	('FN_KAYSER_I_RUM', 1, 'MINOR_CIV_PERGE', NULL, 'ABSORB'),
	('FN_STATO_DA_MAR', 1, 'MINOR_CIV_RAGUSA', NULL, 'UNION'),
	('FN_STATO_DA_MAR', 1, 'MINOR_CIV_TYRE', NULL, 'UNION'),
	('FN_STATO_DA_MAR', 1, 'MINOR_CIV_SIDON', NULL, 'UNION'),
	('FN_STATO_DA_MAR', 1, 'MINOR_CIV_VALLETTA', NULL, 'UNION');
