-- Formable Nations v0.4: more nations, one or two stages each, across all eras. Bonuses follow FN_Data.sql's scale
-- (half to one social policy); Tier II stages also get the proclamation golden age (FN_Perks.sql).

INSERT INTO Policies (Type, Description, Help, IsDummy) VALUES
	('POLICY_FN_SUMER_AKKAD',      'TXT_KEY_FN_SUMER_AKKAD_TITLE',      'TXT_KEY_FN_SUMER_AKKAD_HELP',      1),
	('POLICY_FN_KALMAR',           'TXT_KEY_FN_KALMAR_TITLE',           'TXT_KEY_FN_KALMAR_HELP',           1),
	('POLICY_FN_SWEDISH_EMPIRE',   'TXT_KEY_FN_SWEDISH_EMPIRE_TITLE',   'TXT_KEY_FN_SWEDISH_EMPIRE_HELP',   1),
	('POLICY_FN_RUSSIAN_EMPIRE',   'TXT_KEY_FN_RUSSIAN_EMPIRE_TITLE',   'TXT_KEY_FN_RUSSIAN_EMPIRE_HELP',   1),
	('POLICY_FN_IBERIAN_UNION',    'TXT_KEY_FN_IBERIAN_UNION_TITLE',    'TXT_KEY_FN_IBERIAN_UNION_HELP',    1),
	('POLICY_FN_UNITED_NETHERLANDS','TXT_KEY_FN_UNITED_NETHERLANDS_TITLE','TXT_KEY_FN_UNITED_NETHERLANDS_HELP',1),
	('POLICY_FN_ITALY',            'TXT_KEY_FN_ITALY_TITLE',            'TXT_KEY_FN_ITALY_HELP',            1),
	('POLICY_FN_YUAN',             'TXT_KEY_FN_YUAN_TITLE',             'TXT_KEY_FN_YUAN_HELP',             1);

UPDATE Policies SET MilitaryProductionModifier = 10 WHERE Type = 'POLICY_FN_SWEDISH_EMPIRE';

INSERT INTO Policy_CapitalYieldChanges (PolicyType, YieldType, Yield) VALUES
	('POLICY_FN_SUMER_AKKAD', 'YIELD_SCIENCE', 2),
	('POLICY_FN_SUMER_AKKAD', 'YIELD_FOOD', 2),
	('POLICY_FN_KALMAR', 'YIELD_PRODUCTION', 2),
	('POLICY_FN_KALMAR', 'YIELD_GOLD', 2),
	('POLICY_FN_SWEDISH_EMPIRE', 'YIELD_CULTURE', 2),
	('POLICY_FN_RUSSIAN_EMPIRE', 'YIELD_CULTURE', 2),
	('POLICY_FN_UNITED_NETHERLANDS', 'YIELD_GOLD', 3),
	('POLICY_FN_ITALY', 'YIELD_CULTURE', 3);

INSERT INTO Policy_YieldModifiers (PolicyType, YieldType, Yield) VALUES
	('POLICY_FN_RUSSIAN_EMPIRE', 'YIELD_SCIENCE', 5),
	('POLICY_FN_IBERIAN_UNION', 'YIELD_GOLD', 5),
	('POLICY_FN_UNITED_NETHERLANDS', 'YIELD_PRODUCTION', 5),
	('POLICY_FN_ITALY', 'YIELD_CULTURE', 5),
	('POLICY_FN_YUAN', 'YIELD_GOLD', 5),
	('POLICY_FN_YUAN', 'YIELD_SCIENCE', 5);

INSERT INTO FormableNations
	(Type, Chain, Stage, Tier, IsUnion, CivilizationType, Title, Description, ShortDescription, Adjective, Help, Quote, MinEra, MaxEra, PrereqStage, PrereqTurns, PolicyType)
VALUES
	('FN_SUMER_AKKAD', 'BABYLON', 1, 2, 0, 'CIVILIZATION_BABYLON', 'TXT_KEY_FN_SUMER_AKKAD_TITLE',
		'TXT_KEY_FN_SUMER_AKKAD_DESC', 'TXT_KEY_FN_SUMER_AKKAD_SHORT', 'TXT_KEY_FN_SUMER_AKKAD_ADJ',
		'TXT_KEY_FN_SUMER_AKKAD_HELP', 'TXT_KEY_FN_SUMER_AKKAD_QUOTE', 'ERA_ANCIENT', 'ERA_CLASSICAL', NULL, 0, 'POLICY_FN_SUMER_AKKAD'),
	('FN_KALMAR', 'DENMARK', 1, 1, 1, 'CIVILIZATION_DENMARK', 'TXT_KEY_FN_KALMAR_TITLE',
		NULL, NULL, NULL,
		'TXT_KEY_FN_KALMAR_HELP', 'TXT_KEY_FN_KALMAR_QUOTE', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', NULL, 0, 'POLICY_FN_KALMAR'),
	('FN_SWEDISH_EMPIRE', 'SWEDEN', 1, 2, 0, 'CIVILIZATION_SWEDEN', 'TXT_KEY_FN_SWEDISH_EMPIRE_TITLE',
		'TXT_KEY_FN_SWEDISH_EMPIRE_DESC', 'TXT_KEY_FN_SWEDISH_EMPIRE_SHORT', 'TXT_KEY_FN_SWEDISH_EMPIRE_ADJ',
		'TXT_KEY_FN_SWEDISH_EMPIRE_HELP', 'TXT_KEY_FN_SWEDISH_EMPIRE_QUOTE', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL', NULL, 0, 'POLICY_FN_SWEDISH_EMPIRE'),
	('FN_RUSSIAN_EMPIRE', 'RUSSIA', 1, 2, 0, 'CIVILIZATION_RUSSIA', 'TXT_KEY_FN_RUSSIAN_EMPIRE_TITLE',
		'TXT_KEY_FN_RUSSIAN_EMPIRE_DESC', 'TXT_KEY_FN_RUSSIAN_EMPIRE_SHORT', 'TXT_KEY_FN_RUSSIAN_EMPIRE_ADJ',
		'TXT_KEY_FN_RUSSIAN_EMPIRE_HELP', 'TXT_KEY_FN_RUSSIAN_EMPIRE_QUOTE', 'ERA_RENAISSANCE', 'ERA_INDUSTRIAL', NULL, 0, 'POLICY_FN_RUSSIAN_EMPIRE'),
	('FN_IBERIAN_UNION', 'SPAIN', 1, 1, 1, 'CIVILIZATION_SPAIN', 'TXT_KEY_FN_IBERIAN_UNION_TITLE',
		NULL, NULL, NULL,
		'TXT_KEY_FN_IBERIAN_UNION_HELP', 'TXT_KEY_FN_IBERIAN_UNION_QUOTE', 'ERA_RENAISSANCE', 'ERA_RENAISSANCE', NULL, 0, 'POLICY_FN_IBERIAN_UNION'),
	('FN_UNITED_NETHERLANDS', 'NETHERLANDS', 1, 2, 0, 'CIVILIZATION_NETHERLANDS', 'TXT_KEY_FN_UNITED_NETHERLANDS_TITLE',
		'TXT_KEY_FN_UNITED_NETHERLANDS_DESC', 'TXT_KEY_FN_UNITED_NETHERLANDS_SHORT', 'TXT_KEY_FN_UNITED_NETHERLANDS_ADJ',
		'TXT_KEY_FN_UNITED_NETHERLANDS_HELP', 'TXT_KEY_FN_UNITED_NETHERLANDS_QUOTE', 'ERA_INDUSTRIAL', 'ERA_INDUSTRIAL', NULL, 0, 'POLICY_FN_UNITED_NETHERLANDS'),
	('FN_ITALY', 'ROME', 1, 2, 0, 'CIVILIZATION_ROME', 'TXT_KEY_FN_ITALY_TITLE',
		'TXT_KEY_FN_ITALY_DESC', 'TXT_KEY_FN_ITALY_SHORT', 'TXT_KEY_FN_ITALY_ADJ',
		'TXT_KEY_FN_ITALY_HELP', 'TXT_KEY_FN_ITALY_QUOTE', 'ERA_INDUSTRIAL', 'ERA_MODERN', NULL, 0, 'POLICY_FN_ITALY'),
	('FN_YUAN', 'MONGOL', 1, 2, 0, 'CIVILIZATION_MONGOL', 'TXT_KEY_FN_YUAN_TITLE',
		'TXT_KEY_FN_YUAN_DESC', 'TXT_KEY_FN_YUAN_SHORT', 'TXT_KEY_FN_YUAN_ADJ',
		'TXT_KEY_FN_YUAN_HELP', 'TXT_KEY_FN_YUAN_QUOTE', 'ERA_MEDIEVAL', 'ERA_RENAISSANCE', NULL, 0, 'POLICY_FN_YUAN');

INSERT INTO FormableNation_ClaimGroups (FormableType, GroupID, NumRequired, Description) VALUES
	('FN_SUMER_AKKAD', 1, 1, 'TXT_KEY_FN_GROUP_SUMER'),
	('FN_KALMAR', 1, 1, 'TXT_KEY_FN_GROUP_SWEDEN'),
	('FN_SWEDISH_EMPIRE', 1, 1, 'TXT_KEY_FN_GROUP_LIVONIA'),
	('FN_RUSSIAN_EMPIRE', 1, 1, 'TXT_KEY_FN_GROUP_LIVONIA'),
	('FN_IBERIAN_UNION', 1, 1, 'TXT_KEY_FN_GROUP_PORTUGAL'),
	('FN_UNITED_NETHERLANDS', 1, 1, 'TXT_KEY_FN_GROUP_SOUTHERN_NETHERLANDS'),
	('FN_ITALY', 1, 2, 'TXT_KEY_FN_GROUP_ITALIAN_STATES'),
	('FN_YUAN', 1, 1, 'TXT_KEY_FN_GROUP_CHINA');

INSERT INTO FormableNation_Claims (FormableType, GroupID, MinorCivType, CivilizationType, Mode) VALUES
	('FN_SUMER_AKKAD', 1, 'MINOR_CIV_UR', NULL, 'ABSORB'),
	-- Sweden is Stockholm the City-State when the Swedes are absent (VP blocks it while they play), else their capital.
	('FN_KALMAR', 1, 'MINOR_CIV_STOCKHOLM', NULL, 'UNION'),
	('FN_KALMAR', 1, NULL, 'CIVILIZATION_SWEDEN', 'UNION'),
	-- Riga: the prize of the Great Northern War. Sweden and Russia compete for it.
	('FN_SWEDISH_EMPIRE', 1, 'MINOR_CIV_RIGA', NULL, 'ABSORB'),
	('FN_RUSSIAN_EMPIRE', 1, 'MINOR_CIV_RIGA', NULL, 'ABSORB'),
	('FN_IBERIAN_UNION', 1, 'MINOR_CIV_LISBON', NULL, 'UNION'),
	('FN_IBERIAN_UNION', 1, NULL, 'CIVILIZATION_PORTUGAL', 'UNION'),
	('FN_UNITED_NETHERLANDS', 1, 'MINOR_CIV_BRUSSELS', NULL, 'ABSORB'),
	('FN_UNITED_NETHERLANDS', 1, 'MINOR_CIV_ANTWERP', NULL, 'ABSORB'),
	('FN_ITALY', 1, 'MINOR_CIV_FLORENCE', NULL, 'ABSORB'),
	('FN_ITALY', 1, 'MINOR_CIV_MILAN', NULL, 'ABSORB'),
	('FN_ITALY', 1, 'MINOR_CIV_GENOA', NULL, 'ABSORB'),
	('FN_ITALY', 1, 'MINOR_CIV_VENICE', NULL, 'ABSORB'),
	('FN_YUAN', 1, NULL, 'CIVILIZATION_CHINA', 'OWN');
