-- International organisations (Tier III). Depth: FUNCTIONAL (one game system) or INTERGOVERNMENTAL (multi-purpose,
-- sovereign members). SUPRANATIONAL (EU-style) is designed but not built yet.
CREATE TABLE IF NOT EXISTS FormableNation_Organisations (
	ID integer PRIMARY KEY AUTOINCREMENT,
	Type text NOT NULL UNIQUE,
	Depth text NOT NULL,
	Title text NOT NULL,
	Help text,
	Quote text,
	MinEra text NOT NULL REFERENCES Eras(Type),   -- founder must have reached it
	MaxEra text REFERENCES Eras(Type),            -- dissolves once its founder passes it; NULL = never
	MinMembers integer NOT NULL DEFAULT 3,
	RequiresCoast boolean NOT NULL DEFAULT 0,     -- member capital must be coastal
	ResourceType text REFERENCES Resources(Type), -- members must own at least MinResource of it
	MinResource integer NOT NULL DEFAULT 0,
	TradeRouteGold integer NOT NULL DEFAULT 0,    -- per turn, per trade route a major member runs to another member
	ResourceGold integer NOT NULL DEFAULT 0,      -- per turn, per unit of ResourceType a major member owns (max 10 units)
	MinorInfluence integer NOT NULL DEFAULT 0,    -- per turn, each major member's Influence with each City-State member
	OpenBorders boolean NOT NULL DEFAULT 0,       -- major members keep open borders with each other
	PolicyType text REFERENCES Policies(Type)     -- optional dummy policy for major members
);

-- Eligible peoples. No CivilizationType rows: every major civ may join. No MinorCivType rows: no City-State may join,
-- unless the organisation has a ResourceType, in which case any City-State owning it may.
CREATE TABLE IF NOT EXISTS FormableNation_OrganisationMembers (
	OrganisationType text NOT NULL REFERENCES FormableNation_Organisations(Type),
	CivilizationType text REFERENCES Civilizations(Type),
	MinorCivType text REFERENCES MinorCivilizations(Type)
);

INSERT INTO FormableNation_Organisations
	(Type, Depth, Title, Help, Quote, MinEra, MaxEra, MinMembers, RequiresCoast, ResourceType, MinResource, TradeRouteGold, ResourceGold, MinorInfluence, OpenBorders)
VALUES
	('ORG_HANSEATIC_LEAGUE', 'FUNCTIONAL', 'TXT_KEY_FN_ORG_HANSE_TITLE', 'TXT_KEY_FN_ORG_HANSE_HELP', 'TXT_KEY_FN_ORG_HANSE_QUOTE',
		'ERA_MEDIEVAL', 'ERA_RENAISSANCE', 3, 1, NULL, 0, 3, 0, 1, 0),
	('ORG_OPEC', 'FUNCTIONAL', 'TXT_KEY_FN_ORG_OPEC_TITLE', 'TXT_KEY_FN_ORG_OPEC_HELP', 'TXT_KEY_FN_ORG_OPEC_QUOTE',
		'ERA_POSTMODERN', NULL, 3, 0, 'RESOURCE_OIL', 2, 0, 1, 0, 0),
	('ORG_ARAB_LEAGUE', 'INTERGOVERNMENTAL', 'TXT_KEY_FN_ORG_ARAB_LEAGUE_TITLE', 'TXT_KEY_FN_ORG_INTERGOV_HELP', 'TXT_KEY_FN_ORG_ARAB_LEAGUE_QUOTE',
		'ERA_MODERN', NULL, 3, 0, NULL, 0, 2, 0, 1, 1),
	('ORG_AFRICAN_UNION', 'INTERGOVERNMENTAL', 'TXT_KEY_FN_ORG_AFRICAN_UNION_TITLE', 'TXT_KEY_FN_ORG_INTERGOV_HELP', 'TXT_KEY_FN_ORG_AFRICAN_UNION_QUOTE',
		'ERA_POSTMODERN', NULL, 3, 0, NULL, 0, 2, 0, 1, 1),
	('ORG_ASEAN', 'INTERGOVERNMENTAL', 'TXT_KEY_FN_ORG_ASEAN_TITLE', 'TXT_KEY_FN_ORG_INTERGOV_HELP', 'TXT_KEY_FN_ORG_ASEAN_QUOTE',
		'ERA_POSTMODERN', NULL, 3, 0, NULL, 0, 2, 0, 1, 1),
	('ORG_NORDIC_COUNCIL', 'INTERGOVERNMENTAL', 'TXT_KEY_FN_ORG_NORDIC_TITLE', 'TXT_KEY_FN_ORG_INTERGOV_HELP', 'TXT_KEY_FN_ORG_NORDIC_QUOTE',
		'ERA_POSTMODERN', NULL, 3, 0, NULL, 0, 2, 0, 1, 1),
	('ORG_MERCOSUR', 'INTERGOVERNMENTAL', 'TXT_KEY_FN_ORG_MERCOSUR_TITLE', 'TXT_KEY_FN_ORG_INTERGOV_HELP', 'TXT_KEY_FN_ORG_MERCOSUR_QUOTE',
		'ERA_FUTURE', NULL, 2, 0, NULL, 0, 2, 0, 1, 1);

INSERT INTO FormableNation_OrganisationMembers (OrganisationType, CivilizationType, MinorCivType) VALUES
	-- Hanseatic League: member towns and Kontore (Novgorod's Peterhof, Bergen, Bruges, London's Steelyard)
	('ORG_HANSEATIC_LEAGUE', 'CIVILIZATION_GERMANY', NULL), ('ORG_HANSEATIC_LEAGUE', 'CIVILIZATION_DENMARK', NULL),
	('ORG_HANSEATIC_LEAGUE', 'CIVILIZATION_SWEDEN', NULL), ('ORG_HANSEATIC_LEAGUE', 'CIVILIZATION_NETHERLANDS', NULL),
	('ORG_HANSEATIC_LEAGUE', 'CIVILIZATION_POLAND', NULL), ('ORG_HANSEATIC_LEAGUE', 'CIVILIZATION_ENGLAND', NULL),
	('ORG_HANSEATIC_LEAGUE', 'CIVILIZATION_RUSSIA', NULL),
	('ORG_HANSEATIC_LEAGUE', NULL, 'MINOR_CIV_NOVGOROD'), ('ORG_HANSEATIC_LEAGUE', NULL, 'MINOR_CIV_RIGA'),
	('ORG_HANSEATIC_LEAGUE', NULL, 'MINOR_CIV_STOCKHOLM'), ('ORG_HANSEATIC_LEAGUE', NULL, 'MINOR_CIV_OSLO'),
	('ORG_HANSEATIC_LEAGUE', NULL, 'MINOR_CIV_BRUSSELS'), ('ORG_HANSEATIC_LEAGUE', NULL, 'MINOR_CIV_ANTWERP'),
	('ORG_HANSEATIC_LEAGUE', NULL, 'MINOR_CIV_BRANDENBURG'), ('ORG_HANSEATIC_LEAGUE', NULL, 'MINOR_CIV_COPENHAGEN'),
	('ORG_HANSEATIC_LEAGUE', NULL, 'MINOR_CIV_WINCHESTER'),
	-- Arab League (1945)
	('ORG_ARAB_LEAGUE', 'CIVILIZATION_ARABIA', NULL), ('ORG_ARAB_LEAGUE', 'CIVILIZATION_EGYPT', NULL),
	('ORG_ARAB_LEAGUE', 'CIVILIZATION_MOROCCO', NULL),
	('ORG_ARAB_LEAGUE', NULL, 'MINOR_CIV_SIDON'), ('ORG_ARAB_LEAGUE', NULL, 'MINOR_CIV_TYRE'),
	('ORG_ARAB_LEAGUE', NULL, 'MINOR_CIV_BYBLOS'), ('ORG_ARAB_LEAGUE', NULL, 'MINOR_CIV_MOGADISHU'),
	('ORG_ARAB_LEAGUE', NULL, 'MINOR_CIV_MARRAKECH'), ('ORG_ARAB_LEAGUE', NULL, 'MINOR_CIV_RAQMU'),
	('ORG_ARAB_LEAGUE', NULL, 'MINOR_CIV_ORMUS'),
	-- African Union (OAU 1963)
	('ORG_AFRICAN_UNION', 'CIVILIZATION_ETHIOPIA', NULL), ('ORG_AFRICAN_UNION', 'CIVILIZATION_ZULU', NULL),
	('ORG_AFRICAN_UNION', 'CIVILIZATION_SONGHAI', NULL), ('ORG_AFRICAN_UNION', 'CIVILIZATION_MOROCCO', NULL),
	('ORG_AFRICAN_UNION', 'CIVILIZATION_EGYPT', NULL), ('ORG_AFRICAN_UNION', 'CIVILIZATION_CARTHAGE', NULL),
	('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_MOMBASA'), ('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_ZANZIBAR'),
	('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_CAPE_TOWN'), ('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_MBANZA_KONGO'),
	('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_IFE'), ('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_ANTANANARIVO'),
	('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_MOGADISHU'), ('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_KUMASI'),
	('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_BORNU'), ('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_SOKOTO'),
	('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_OUGADOUGOU'), ('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_SEGOU'),
	('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_LUBA'), ('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_BUNKEYA'),
	('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_AKSUM'), ('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_DJENNE'),
	('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_KWA_BULAWAYO'), ('ORG_AFRICAN_UNION', NULL, 'MINOR_CIV_MARRAKECH'),
	-- ASEAN (1967)
	('ORG_ASEAN', 'CIVILIZATION_SIAM', NULL), ('ORG_ASEAN', 'CIVILIZATION_INDONESIA', NULL),
	('ORG_ASEAN', NULL, 'MINOR_CIV_HANOI'), ('ORG_ASEAN', NULL, 'MINOR_CIV_MANILA'),
	('ORG_ASEAN', NULL, 'MINOR_CIV_KUALA_LUMPUR'), ('ORG_ASEAN', NULL, 'MINOR_CIV_SINGAPORE'),
	('ORG_ASEAN', NULL, 'MINOR_CIV_MALACCA'), ('ORG_ASEAN', NULL, 'MINOR_CIV_JAKARTA'),
	-- Nordic Council (1952)
	('ORG_NORDIC_COUNCIL', 'CIVILIZATION_DENMARK', NULL), ('ORG_NORDIC_COUNCIL', 'CIVILIZATION_SWEDEN', NULL),
	('ORG_NORDIC_COUNCIL', NULL, 'MINOR_CIV_OSLO'), ('ORG_NORDIC_COUNCIL', NULL, 'MINOR_CIV_HELSINKI'),
	('ORG_NORDIC_COUNCIL', NULL, 'MINOR_CIV_STOCKHOLM'), ('ORG_NORDIC_COUNCIL', NULL, 'MINOR_CIV_COPENHAGEN'),
	-- Mercosur (1991)
	('ORG_MERCOSUR', 'CIVILIZATION_BRAZIL', NULL),
	('ORG_MERCOSUR', NULL, 'MINOR_CIV_BUENOS_AIRES'), ('ORG_MERCOSUR', NULL, 'MINOR_CIV_RIO_DE_JANEIRO'),
	('ORG_MERCOSUR', NULL, 'MINOR_CIV_BOGOTA');
