"""Build VP's gamecore DLL with CivVNeo's portable toolchain (toolchain B, no installers, no admin rights).

Toolchain on D:\\Toolchains (see README, "Engine builds"):
  SDK70\\        Windows SDK 7.0 + VC9 headers/libraries, extracted from the SDK 7.0 ISO with `msiexec /a`
  LLVM-20.1.8\\  clang-cl, lld-link, llvm-lib and clang's own headers from the LLVM 20.1.8 Windows archive
  Python312\\    the embeddable Windows Python that runs this script

It runs upstream's build_vp_clang_sdk.py unchanged except for its hard-coded C:\\Program Files paths and the commit-id
step, which is done here (Windows git may refuse a checkout made from WSL). Output:
upstream\\Community-Patch-DLL\\clang-output\\<Config>\\CvGameCore_Expansion2.dll and build.log.

Usage: D:\\Toolchains\\Python312\\python.exe tools\\build_dll.py --config release [--version TEXT]
"""
import os
import sys
from pathlib import Path

TOOLS = Path(os.environ.get("CIVVNEO_TOOLCHAINS", r"D:\Toolchains"))
SDK = TOOLS / "SDK70" / "Program Files" / "Microsoft SDKs" / "Windows" / "v7.0"
VC = TOOLS / "SDK70" / "Program Files" / "Microsoft Visual Studio 9.0" / "Vc7"
LLVM = TOOLS / "LLVM-20.1.8" / "bin"
UPSTREAM = Path(__file__).resolve().parents[1] / "upstream" / "Community-Patch-DLL"


def main():
    version = "CivVNeo"
    if "--version" in sys.argv:
        i = sys.argv.index("--version")
        version = sys.argv[i + 1]
        del sys.argv[i:i + 2]
    for p in (SDK / "Include" / "Windows.h", VC / "include" / "crtdefs.h", LLVM / "clang-cl.exe"):
        if not p.exists():
            sys.exit(f"missing toolchain file: {p}")

    src = (UPSTREAM / "build_vp_clang_sdk.py").read_text(encoding="utf-8")
    replacements = {
        r"C:\Program Files (x86)\Microsoft SDKs\Windows\v{SDK_VERSION}": str(SDK),
        r"C:\Program Files (x86)\Microsoft SDKs\Windows\v{sdk_version}": str(SDK),
        r"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC": str(VC),
        "subprocess.run('update_commit_id.bat', capture_output=True)": "subprocess.run('cmd /c exit 0', capture_output=True)",
        # VP's CI lets clang detect VC9's cl.exe on PATH and match its ABI. Clang only recognises an old-style
        # "...\\VC\\bin" directory, and ours is "Vc7" (the msiexec /a layout), so the version is given explicitly.
        # Without it clang assumes a modern MSVC and emits thread-safe statics, sized delete and __std_terminate,
        # which VC9's runtime does not have.
        "args = ['-m32', '-msse3',": "args = ['-m32', '-msse3', '-fms-compatibility-version=15.00.30729',",
    }
    for old, new in replacements.items():
        if old not in src:
            sys.exit(f"upstream build script changed; cannot find: {old}")
        src = src.replace(old, new)

    (UPSTREAM / "commit_id.inc").write_text(
        f'const char CURRENT_GAMECORE_VERSION[] = "{version}"; //autogenerated by tools/build_dll.py\n', encoding="ascii")
    os.environ["PATH"] = f"{LLVM};" + os.environ["PATH"]
    os.chdir(UPSTREAM)
    exec(compile(src, str(UPSTREAM / "build_vp_clang_sdk.py"), "exec"), {"__name__": "__main__", "__file__": str(UPSTREAM / "build_vp_clang_sdk.py")})


if __name__ == "__main__":
    main()
